name: islamic_finance_education
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.19.0
  markdown_widget: ^2.3.2+8
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
